name: Terraform Deployment  # Workflow name

on:  
  push:                  # Trigger on pushes to the repository
    branches: 
      - main             # Triggers for pushes to the 'main' branch (adjust branches as needed)

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest # Job runs on an Ubuntu runner

    # Environment Setup
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}           # Example: 'eu-west-1' 

    steps:
      - name: Checkout
        uses: actions/checkout@v3   # Check out repository code

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
           terraform_version: 1.x.x   # Specify your desired Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        run: terraform apply -auto-approve  # Auto-approve for the pipeline

