name: Terraform Deployment

on:  
  push:
    branches: 
      - main

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    # Environment Setup
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
           terraform_version: 1.7

      - name: Terraform Init
        working-directory: ./Task-5
        run: ls -a && terraform init

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: Email Notification 
        if: ${{ always() }} # Adjust condition as needed
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Example for Gmail, update accordingly
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Terraform Deployment Status
          body: "Deployment status: ${{ job.status }}" # Include any relevant details
          to: brian.connolly71@gmail.com 
          from: terraform-notifier@example.com 
          content_type: text/plain 
