name: Terraform Deployment

on:  
  push:
    branches: 
      - main

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TEST_VAR: "justTesting"

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7
      
      - name: Print AWS Credentials (debugging)
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY" 
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
          echo "TEST_VAR: $TEST_VAR"
               

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        run: terraform apply -auto-approve
